# Generated by Django 4.2.25 on 2025-10-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='mock', max_length=32)),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_secret', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('requires_confirmation', 'Requires Confirmation'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='requires_confirmation', max_length=32)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
