# Generated by Django 4.2.25 on 2025-10-12 19:02

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default=bookings.models.gen_code, editable=False, max_length=24, unique=True),
        ),
    ]
